services:
  app:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '8gb'
    volumes:
      - ./:/workdir
    working_dir: /workdir
    ports:
      - "8888:8888"
      - "10022:22"
    tty: true